# Generated by Django 5.0.1 on 2025-06-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma-separated list of technologies', max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text='Font Awesome icon name without the fa- prefix', max_length=50),
        ),
    ]
