# Generated by Django 5.0.1 on 2025-06-24 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_service_price_service_tech_stack_alter_service_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='achievements',
            field=models.JSONField(blank=True, default=list, help_text='Notable achievements and certifications'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 24, 8, 43, 51, 52468, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='department',
            field=models.CharField(blank=True, help_text='Department or team', max_length=50),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, help_text='Professional email address', max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='github',
            field=models.URLField(blank=True, help_text='GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_leadership',
            field=models.BooleanField(default=False, help_text='Is this member part of leadership team?'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skills and technologies'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of professional experience'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(help_text='Professional biography'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(help_text='Profile image', upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this member currently active?'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(help_text='Full name of the team member', max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(help_text='Job title or position', max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter',
            field=models.URLField(blank=True, help_text='Twitter profile URL'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['is_active', 'order'], name='website_tea_is_acti_1b6c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['is_leadership', 'order'], name='website_tea_is_lead_e47d29_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['department'], name='website_tea_departm_b19f81_idx'),
        ),
    ]
