# Generated by Django 5.0.1 on 2025-06-25 14:06

import django.core.validators
import website.models
import website.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_teammember_options_teammember_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Image file (max 5MB, jpg/png/gif only)', null=True, storage=website.storage.SecureFileStorage(), upload_to='services/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), website.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(help_text='Profile image (max 5MB, jpg/png only)', storage=website.storage.SecureFileStorage(), upload_to='team/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), website.models.validate_file_size]),
        ),
    ]
